/* ===================== SPECIES DATA ===================== */
// hab: kennel desert swamp reptile bigcat sky mud pachy jungle ice salt jurassic
// headSig: grafts this species donates onto a mashup FACE when it's the BODY donor; bodySig: what it donates onto the body when it's the FACE donor
// ident: identity accessories that travel with the face
const SP = {};
function sp(id, o) { o.id = id; o.kit = Object.assign({ id, seed: hashStr(id) % 9999 + 1, skin: 'fur' }, o.kit); o.kit.headType = o.kit.headType || 'dog'; SP[id] = o; }
// ---------------- Act 1: dogs & cats ----------------
sp('meatball', { name: 'Meatball', sp: 'Pug', cls: 'pet', act: 1, size: 1, cute: 5, scary: 1, hab: 'kennel', voice: 'snort', diet: 'kibble', fee: 90, tags: ['Cuddly', 'Apartment', 'Lazy'], traits: ['lazy', 'gassy'], sigName: V('Belly rub (brace for impact)', 'Belly rub'), pre: 'Pug', suf: 'pug', lbs: 18, kit: { plan: 'sit', W: 42, H: 46, col: '#d9b98a', tail: 'curl', belly: '#ecd6b0', hp: { col: '#d9b98a', snout: .08, ears: 'fold', wrinkle: 1, muz: '#3a2e2a', er: 6.5, tongue: 1, eye: '#3a2412' } } });
sp('chancla', { name: 'Chancla', sp: 'Chihuahua', cls: 'pet', act: 1, size: 1, cute: 5, scary: 2, hab: 'kennel', voice: 'yap', diet: 'kibble', fee: 80, tags: ['Tiny', 'Purse-size', 'Loud'], traits: ['fierce', 'tiny'], sigName: 'Calm-down cuddle', pre: 'Chihua', suf: 'huahua', lbs: 4, ident: ['shiver'], kit: { plan: 'sit', W: 32, H: 36, col: '#e3b27b', tail: 'thin', belly: '#f1d2a8', hs: 1.12, bodyGrafts: ['shiver'], hp: { col: '#e3b27b', snout: .22, ears: 'bat', earS: .95, er: 7, muz: '#f1d2a8', eye: '#3b2412', browUp: 1 } } });
sp('barksalot', { name: 'Sir Barksalot', sp: 'Basset hound', cls: 'pet', act: 1, size: 2, cute: 4, scary: 1, hab: 'kennel', voice: 'howl', diet: 'kibble', fee: 110, tags: ['Lazy', 'Gentle', 'Porch'], traits: ['dramatic', 'lazy'], sigName: 'Ear wash', pre: 'Bass', suf: 'basset', lbs: 55, kit: { plan: 'quad', L: 98, H: 38, leg: 16, lw: 14, col: '#c58a4a', belly: '#f4ead6', tail: 'whip', hp: { col: '#c58a4a', snout: .8, ears: 'long', lid: .42, muz: '#f4ead6', blaze: 1, eye: '#5a3418' } } });
sp('tamale', { name: 'Tamale', sp: 'Long-haired dachshund', cls: 'pet', act: 1, size: 1, cute: 5, scary: 1, hab: 'kennel', voice: 'yap', diet: 'kibble', fee: 100, tags: ['Cuddly', 'Apartment', 'Cozy'], traits: ['cozy', 'stubborn'], sigName: 'Re-wrap the burrito', pre: 'Hot Dog', suf: 'dachs', lbs: 11, ident: ['blanket'], kit: { plan: 'quad', L: 104, H: 30, leg: 12, lw: 11, col: '#8a4a24', tail: 'bushy', bodyGrafts: ['blanket'], hp: { col: '#8a4a24', snout: .9, ears: 'flop', muz: '#a8643a', eye: '#3a1a0a' } } });
sp('kevin', { name: 'Kevin', sp: 'Orange tabby', cls: 'pet', act: 1, size: 1, cute: 4, scary: 1, hab: 'kennel', voice: 'meow', diet: 'kibble', fee: 70, tags: ['Kid-friendly', 'Chaotic', 'Funny'], traits: ['dumb', 'chaotic'], sigName: 'Laser practice', pre: 'Purr', suf: 'kitty', lbs: 13, kit: { plan: 'sit', W: 42, H: 50, col: '#ee9a43', pat: 'tabby', patCol: '#c06a22', belly: '#fbe6c8', tail: 'thin', hp: { col: '#ee9a43', headType: 'cat', stripes: '#c06a22', ir: .22, eye: '#9ab84a' }, headType: 'cat' } });
sp('duchess', { name: 'Duchess Meowington', sp: 'Persian', cls: 'pet', act: 1, size: 1, cute: 4, scary: 2, hab: 'kennel', voice: 'meow', diet: 'kibble', fee: 150, tags: ['Fancy', 'Quiet', 'Diva'], traits: ['snooty', 'diva'], sigName: 'Royal blowout', pre: 'Meow', suf: 'meowington', lbs: 10, ident: ['tiara'], kit: { plan: 'sit', W: 48, H: 42, col: '#fbf7f2', tail: 'bushy', headType: 'cat', headGrafts: ['tiara'], hp: { col: '#fbf7f2', flat: 1, ears: 'small', eye: '#d8a12e', lid: .45, lidTilt: 1.2 } } });
sp('taco', { name: 'Taco Tuesday', sp: 'Pit bull mix', cls: 'pet', act: 1, size: 2, cute: 5, scary: 2, hab: 'kennel', voice: 'bark', diet: 'kibble', fee: 120, tags: ['Playful', 'Active', 'Kid-friendly'], traits: ['happy', 'scaredy'], sigName: 'Tumbleweed bravery', pre: 'Taco', suf: 'bull', lbs: 60, kit: { plan: 'sit', W: 50, H: 56, col: '#9a7050', pat: 'brindle', patCol: '#4a3020', belly: '#f4ead6', tail: 'whip', hp: { col: '#9a7050', snout: .4, ears: 'fold', grin: 1, er: 5.4, blaze: 1, muz: '#f4ead6', eye: '#5a3418' } } });
sp('boots', { name: 'Boots', sp: 'Tuxedo cat', cls: 'pet', act: 1, size: 1, cute: 4, scary: 1, hab: 'kennel', voice: 'meow', diet: 'kibble', fee: 75, tags: ['Escape artist', 'Playful', 'Apartment'], traits: ['sneaky', 'curious'], sigName: 'Roll call', pre: 'Tux', suf: 'cat', lbs: 9, kit: { plan: 'sit', W: 40, H: 50, col: '#26262e', belly: '#f8f4ec', tail: 'thin', headType: 'cat', hp: { col: '#26262e', tux: 1, eye: '#e8c840', muz: '#f8f4ec' } } });
sp('churro', { name: 'Churro', sp: 'Golden retriever pup', cls: 'pet', act: 1, size: 2, cute: 5, scary: 1, hab: 'kennel', voice: 'bark', diet: 'everything', fee: 140, tags: ['Kid-friendly', 'Playful', 'Big yard'], traits: ['hungry', 'sweet'], sigName: 'X-ray: what did he eat?', pre: 'Golden', suf: 'triever', lbs: 35, ident: ['sock'], kit: { plan: 'sit', W: 46, H: 50, col: '#e8b060', tail: 'bushy', belly: '#f4d090', headGrafts: ['sock'], hp: { col: '#e8b060', snout: .42, ears: 'flop', muz: '#f4d090', eye: '#5a3418' } } });
sp('pelon', { name: 'Pelón', sp: 'Sphynx cat', cls: 'pet', act: 1, size: 1, cute: 3, scary: 2, hab: 'kennel', voice: 'meow', diet: 'kibble', fee: 95, tags: ['Indoor', 'Cuddly', 'Weird'], traits: ['cold', 'clingy'], sigName: 'Sweater fitting', pre: 'Bald', suf: 'sphynx', lbs: 8, kit: { plan: 'sit', W: 38, H: 52, col: '#eec0b0', skin: 'wrinkle', tail: 'thin', sweater: ['#3fa0d8', '#ffd24a'], headType: 'cat', hp: { col: '#eec0b0', sphynx: 1, earS: 1.5, eye: '#7ad0a0', ir: .45 } } });
sp('lowrider', { name: 'Lowrider', sp: 'Corgi', cls: 'pet', act: 1, size: 1, cute: 5, scary: 1, hab: 'kennel', voice: 'bark', diet: 'kibble', fee: 130, tags: ['Active', 'Hiker', 'Playful'], traits: ['speedy', 'proud'], sigName: 'Hop check', pre: 'Cor', suf: 'corgi', lbs: 28, kit: { plan: 'quad', L: 86, H: 36, leg: 12, lw: 12, col: '#e08a3c', belly: '#fbf1e0', tail: 'stub', tailCol: '#fbf1e0', hp: { col: '#e08a3c', snout: .5, ears: 'up', earS: 1.15, muz: '#fbf1e0', blaze: 1, eye: '#4a2810' } } });
sp('sarge', { name: 'Sarge', sp: 'Retired military working dog', cls: 'sidekick', act: 1, size: 3, cute: 4, scary: 3, hab: 'kennel', voice: 'woof', diet: 'kibble', fee: 0, tags: ['Loyal', 'Calm'], traits: ['loyal', 'stoic'], sigName: 'Morning PT', pre: 'Shep', suf: 'herd', lbs: 75, ident: ['dogtags'], kit: { plan: 'sit', W: 50, H: 64, col: '#c58a48', pat: 'shepherd', tail: 'bushy', tailCol: '#5a4030', bodyGrafts: ['dogtags'], hp: { col: '#c58a48', snout: .78, ears: 'up', earS: 1.2, mask: '#2b2420', grey: 1, muz: '#a87040', eye: '#5a3418' } } });
// ---------------- Act 2: unusual animals ----------------
sp('coyote', { name: 'Señor Sneaky', sp: 'Coyote', cls: 'exotic', act: 2, size: 2, cute: 3, scary: 3, hab: 'desert', voice: 'howl', diet: 'mixed', fee: 1500, tags: ['Sneaky', 'Desert', 'Night owl'], traits: ['sneaky', 'charming'], sigName: 'Shoe recovery', pre: 'Coy', suf: 'yote', lbs: 30, bodySig: ['bushytail'], kit: { plan: 'quad', L: 100, H: 38, leg: 38, lw: 11, col: '#b89468', belly: '#efe2c8', tail: 'bushy', tailTip: '#2a2420', hp: { col: '#b89468', snout: .95, ears: 'up', earS: 1.25, muz: '#efe2c8', eye: '#c89a30' } } });
sp('gator', { name: 'Lady Chompington', sp: 'Alligator', cls: 'exotic', act: 2, size: 4, cute: 1, scary: 5, hab: 'swamp', voice: 'hiss', diet: 'fish', fee: 4000, tags: ['Pool', 'Scaly', 'Tough'], traits: ['clingy', 'bitey'], sigName: 'Sunbathing schedule', pre: 'Alli', suf: 'gator', lbs: 500, ident: ['bow'], bodySig: ['spikes'], kit: { plan: 'low', L: 170, H: 28, col: '#5e8a46', skin: 'scales', spikeCol: '#3c5e2e', tail: 'taper', bodyGrafts: ['spikes'], headType: 'gator', headGrafts: ['bow'], hp: { col: '#5e8a46', lashes: 1 } } });
sp('gila', { name: 'Gilbert', sp: 'Gila monster', cls: 'exotic', act: 2, size: 2, cute: 2, scary: 3, hab: 'reptile', voice: 'hiss', diet: 'eggs', fee: 2000, tags: ['Scaly', 'Lazy', 'Desert'], traits: ['grumpy', 'sleepy'], sigName: 'Heat rock', pre: 'Gila', suf: 'monster', lbs: 4, bodySig: ['beads'], kit: { plan: 'low', L: 124, H: 22, col: '#2a1d18', pat: 'beads', skin: 'scales', tail: 'taper', tailLen: 1, headType: 'lizard', hp: { col: '#2a1d18', pat: 'beads', tongue: 1 } } });
sp('lion', { name: 'King Darryl', sp: 'Lion', cls: 'exotic', act: 2, size: 4, cute: 3, scary: 4, hab: 'bigcat', voice: 'roar', diet: 'meat', fee: 12000, tags: ['Showy', 'Big cat', 'Shy'], traits: ['majestic', 'shy'], sigName: 'Mane blowout', pre: 'Li', suf: 'lion', lbs: 420, headSig: ['mane'], kit: { plan: 'quad', L: 118, H: 50, leg: 40, lw: 15, col: '#d8a050', belly: '#f0d8a8', tail: 'tuft', tuftCol: '#7a4818', headType: 'cat', headGrafts: ['mane'], hp: { col: '#d8a050', muz: '#f6e6c8', ears: 'small', eye: '#c08020', brows: 1, maneCol: '#9a5a1e' } } });
sp('tiger', { name: 'Sequins', sp: 'Bengal tiger', cls: 'exotic', act: 2, size: 4, cute: 3, scary: 4, hab: 'bigcat', voice: 'roar', diet: 'meat', fee: 12000, tags: ['Showy', 'Big cat', 'Diva'], traits: ['diva', 'showy'], sigName: 'Spotlight', pre: 'Ti', suf: 'tiger', lbs: 400, bodySig: ['stripes'], kit: { plan: 'quad', L: 122, H: 48, leg: 40, lw: 15, col: '#ec8a2a', pat: 'stripes', patCol: '#2a1a14', belly: '#fbf1e0', tail: 'thin', headType: 'cat', hp: { col: '#ec8a2a', stripes: '#2a1a14', cheeks: '#fbf1e0', eye: '#7ac040', muz: '#fbf1e0' } } });
sp('eagle', { name: 'Freedom', sp: 'Bald eagle', cls: 'exotic', act: 2, size: 2, cute: 2, scary: 3, hab: 'sky', voice: 'screech', diet: 'fish', fee: 5000, tags: ['Flyer', 'Loud', 'Tough'], traits: ['loud', 'proud'], sigName: 'Dawn flag drill', pre: 'Ea', suf: 'eagle', lbs: 12, bodySig: ['wings'], kit: { plan: 'perch', col: '#5a3418', skin: 'feather', tailCol: '#fbf8f0', headType: 'bird', hp: { col: '#fbf8f0', beak: 'hook', fierce: 1 } } });
sp('rhino', { name: 'Rhonda', sp: 'White rhino', cls: 'exotic', act: 2, size: 5, cute: 2, scary: 4, hab: 'mud', voice: 'grunt', diet: 'hay', fee: 20000, tags: ['Tough', 'Needs acreage', 'Clumsy'], traits: ['nearsighted', 'chargey'], sigName: 'Mud spa', pre: 'Rhin', suf: 'oceros', lbs: 5000, ident: ['glasses'], headSig: ['horn'], kit: { plan: 'quad', L: 140, H: 62, leg: 38, lw: 24, foot: 'hoof', col: '#a3a6ab', skin: 'wrinkle', pat: 'mud', tail: 'stub', headType: 'rhino', headGrafts: ['horn', 'glasses'], hs: .95, hp: { col: '#a3a6ab' } } });
sp('python', { name: 'Noodle', sp: 'Reticulated python', cls: 'exotic', act: 2, size: 3, cute: 2, scary: 4, hab: 'reptile', voice: 'hiss', diet: 'weekly', fee: 3000, tags: ['Cuddly', 'Scaly', 'Long'], traits: ['huggy', 'clingy'], sigName: 'Hug release', pre: 'Py', suf: 'conda', lbs: 200, bodySig: ['saddle'], kit: { plan: 'serpent', col: '#c8a060', pat: 'saddle', patCol: '#5a3a1a', thick: 26, headType: 'snake', hp: { col: '#c8a060', cap: '#8a6a3a' } } });
sp('rattler', { name: 'Maracas', sp: 'Diamondback rattlesnake', cls: 'exotic', act: 2, size: 2, cute: 1, scary: 4, hab: 'reptile', voice: 'rattle', diet: 'mice', fee: 2500, tags: ['Musical', 'Scaly', 'Desert'], traits: ['musical', 'cool'], sigName: 'Jam session', pre: 'Rattle', suf: 'rattler', lbs: 6, bodySig: ['rattle'], kit: { plan: 'serpent', col: '#c0a070', pat: 'diamond', patCol: '#6a4a2a', tail: 'rattle', thick: 18, coil: [[-80, -12], [-50, -22], [-20, -14], [10, -10], [36, -24], [24, -50], [-4, -58], [0, -84], [24, -94]], headType: 'snake', hp: { col: '#c0a070', eye: '#e0a020' } } });
sp('elephant', { name: 'Peanut', sp: 'African elephant', cls: 'exotic', act: 2, size: 6, cute: 4, scary: 2, hab: 'pachy', voice: 'trumpet', diet: 'hay', fee: 25000, tags: ['Gentle', 'Needs acreage', 'Pool'], traits: ['gentle', 'scaredy'], sigName: 'Trunk shower', pre: 'Ele', suf: 'phant', lbs: 12000, headSig: ['trunk', 'bigears'], kit: { plan: 'quad', L: 150, H: 80, leg: 50, lw: 28, foot: 'pad', col: '#9aa0a8', skin: 'wrinkle', tail: 'thin', tailS: .7, headType: 'ele', headGrafts: ['bigears', 'trunk', 'tusks'], hs: .9, hp: { col: '#9aa0a8' } } });
sp('trex', { name: 'Tiny', sp: 'Baby T-rex', cls: 'exotic', act: 2, size: 3, cute: 3, scary: 5, hab: 'jurassic', voice: 'roar', diet: 'meat', fee: 0, story: 1, tags: ['Tough', 'Scary', 'Hungry'], traits: ['bitey', 'sad'], sigName: 'Clap assist', pre: 'Rex', suf: 'saurus', lbs: 300, bodySig: ['tinyarms'], kit: { plan: 'dino', col: '#7fae5a', skin: 'scales', belly: '#efe2b6', headType: 'trex', hp: { col: '#7fae5a' } } });
sp('tri', { name: 'Trish', sp: 'Triceratops', cls: 'exotic', act: 2, size: 5, cute: 3, scary: 3, hab: 'jurassic', voice: 'grunt', diet: 'plants', fee: 18000, tags: ['Gentle', 'Needs acreage', 'Tough'], traits: ['hungry', 'gentle'], sigName: 'Horn polish', pre: 'Tri', suf: 'tops', lbs: 13000, headSig: ['frill', 'horn3'], kit: { plan: 'quad', L: 140, H: 58, leg: 34, lw: 20, foot: 'hoof', col: '#8a9a5a', skin: 'scales', tail: 'taper', tailLen: .9, headType: 'tri', headGrafts: ['frill', 'horn3'], hp: { col: '#8a9a5a' } } });
sp('javelina', { name: 'Pork Chop', sp: 'Javelina', cls: 'exotic', act: 2, size: 2, cute: 2, scary: 2, hab: 'desert', voice: 'grunt', diet: 'cactus', fee: 1000, tags: ['Smelly', 'Desert', 'Gang leader'], traits: ['stinky', 'proud'], sigName: 'Smell-o-meter', pre: 'Javel', suf: 'lina', lbs: 50, bodySig: ['bristles'], kit: { plan: 'quad', L: 92, H: 40, leg: 22, lw: 10, foot: 'hoof', col: '#5a5048', skin: 'bristle', tail: 'stub', bodyGrafts: ['bristles'], headType: 'pig', hp: { col: '#5a5048' } } });
sp('roadrunner', { name: 'Zoom', sp: 'Roadrunner', cls: 'exotic', act: 2, size: 1, cute: 3, scary: 1, hab: 'desert', voice: 'coo', diet: 'bugs', fee: 800, tags: ['Fast', 'Desert', 'Hyper'], traits: ['speedy', 'chatty'], sigName: 'Catch for a check-up', pre: 'Road', suf: 'runner', lbs: 1, headSig: ['crest'], bodySig: ['birdlegs'], kit: { plan: 'runner', col: '#7a6a50', skin: 'feather', headType: 'bird', headGrafts: ['crest'], hp: { col: '#7a6a50', beak: 'long', beakCol: '#3a3a3a', patch: '#5aa0d0', eye: '#e0a020' } } });
sp('penguin', { name: 'Frosty Fernando', sp: 'Emperor penguin', cls: 'exotic', act: 2, size: 2, cute: 5, scary: 1, hab: 'ice', voice: 'honk', diet: 'fish', fee: 8000, tags: ['Formal', 'Cold', 'Pool'], traits: ['polite', 'sweaty'], sigName: 'AC management', pre: 'Pen', suf: 'guin', lbs: 80, bodySig: ['flippers'], kit: { plan: 'peng', col: '#24242e', skin: 'feather', headType: 'penguin', hp: { col: '#24242e' } } });
sp('gorilla', { name: 'Big Dave', sp: 'Silverback gorilla', cls: 'exotic', act: 2, size: 4, cute: 3, scary: 3, hab: 'jungle', voice: 'grunt', diet: 'fruit', fee: 15000, tags: ['Strong', 'Dad energy', 'Gentle'], traits: ['dad', 'strong'], sigName: 'Rate his dad joke', pre: 'Goril', suf: 'rilla', lbs: 400, kit: { plan: 'ape', col: '#3a3434', silver: 1, headType: 'ape', hp: { col: '#3a3434', face: '#5a4a48' } } });
sp('hippo', { name: 'Hippolyta', sp: 'Hippo', cls: 'exotic', act: 2, size: 5, cute: 3, scary: 4, hab: 'swamp', voice: 'grunt', diet: 'grass', fee: 20000, tags: ['Pool', 'Needs acreage', 'Territorial'], traits: ['bossy', 'queenly'], sigName: 'Tooth brushing', pre: 'Hip', suf: 'potamus', lbs: 3000, kit: { plan: 'quad', L: 140, H: 66, leg: 24, lw: 22, foot: 'pad', col: '#9a8aa8', belly: '#e8b8c0', tail: 'stub', headType: 'hippo', hs: .95, hp: { col: '#9a8aa8', lashes: 1 } } });
sp('flamingo', { name: 'Flamenca', sp: 'Flamingo', cls: 'exotic', act: 2, size: 1, cute: 4, scary: 1, hab: 'sky', voice: 'honk', diet: 'shrimp', fee: 3000, tags: ['Fancy', 'Dancer', 'Flyer'], traits: ['graceful', 'dramatic'], sigName: 'Pink check', pre: 'Flamin', suf: 'mingo', lbs: 8, bodySig: ['birdlegs'], kit: { plan: 'flamingo', col: '#f490b0', skin: 'feather', headType: 'bird', hp: { col: '#f490b0', beak: 'bent', beakCol: '#f8e8d8', eye: '#f4c13a' } } });
sp('sloth', { name: 'Rápido', sp: 'Sloth', cls: 'exotic', act: 2, size: 1, cute: 5, scary: 1, hab: 'jungle', voice: 'sigh', diet: 'leaves', fee: 5000, tags: ['Calm', 'Slow', 'Cuddly'], traits: ['slow', 'zen'], sigName: 'Leave him alone', pre: 'Slo', suf: 'sloth', lbs: 12, bodySig: ['claws'], kit: { plan: 'ape', col: '#a89070', slouch: 1, foot: 'sloth', chestCol: '#c8b090', headType: 'ape', hp: { col: '#a89070', sloth: 1, face: '#e8d8b8' } } });
sp('kangaroo', { name: 'Joey Two-Pouch', sp: 'Kangaroo', cls: 'exotic', act: 2, size: 3, cute: 3, scary: 3, hab: 'desert', voice: 'grunt', diet: 'grass', fee: 6000, tags: ['Jumper', 'Fighter', 'Active'], traits: ['scrappy', 'sticky-fingered'], sigName: 'Pouch inspection', pre: 'Kanga', suf: 'roo', lbs: 150, bodySig: ['pouch'], kit: { plan: 'roo', col: '#c08a5a', belly: '#e8d0b0', bodyGrafts: ['pouch'], headType: 'rabbit', hp: { col: '#c08a5a', ears: 'roo', teeth: false, muz: '#e8d0b0' } } });
sp('mammoth', { name: 'Woolly Willie', sp: 'Woolly mammoth', cls: 'exotic', act: 2, size: 6, cute: 3, scary: 2, hab: 'ice', voice: 'trumpet', diet: 'hay', fee: 0, story: 1, tags: ['Fluffy', 'Needs acreage', 'Cold'], traits: ['sweaty', 'gentle'], sigName: 'Shave or chill', pre: 'Mam', suf: 'moth', lbs: 14000, headSig: ['tusks'], bodySig: ['wool'], kit: { plan: 'quad', L: 150, H: 84, leg: 44, lw: 28, foot: 'pad', hump: 14, col: '#7a5034', skin: 'wool', tail: 'thin', tailS: .7, bodyGrafts: ['wool'], headType: 'ele', headGrafts: ['trunk', 'tusks'], hs: .9, hp: { col: '#7a5034', wool: 1 } } });
sp('octopus', { name: 'Octavia', sp: 'Giant Pacific octopus', cls: 'exotic', act: 2, size: 2, cute: 3, scary: 2, hab: 'salt', voice: 'blub', diet: 'crab', fee: 7000, tags: ['Many arms', 'Pool', 'Clever'], traits: ['clever', 'sneaky'], sigName: 'Escape check', pre: 'Octo', suf: 'topus', lbs: 60, bodySig: ['tentacles'], kit: { plan: 'octo', col: '#d86a5a', skin: 'smooth', headType: 'octo', hp: { col: '#d86a5a' } } });
// legends
sp('tarantula', { name: 'Hairy Larry', sp: 'Desert tarantula', cls: 'legend', act: 2, size: 1, cute: 2, scary: 4, hab: 'reptile', voice: 'squeak', diet: 'crickets', fee: 500, tags: ['Many legs', 'Shy', 'Desert'], traits: ['shy', 'polite'], sigName: 'Sock check', pre: 'Taran', suf: 'tula', lbs: .2, bodySig: ['spiderlegs'], kit: { plan: 'spider', col: '#5a4030', socks: 1, headType: 'spider', hp: { col: '#5a4030' } } });
sp('skunk', { name: 'Perfume', sp: 'Striped skunk', cls: 'legend', act: 2, size: 1, cute: 4, scary: 1, hab: 'desert', voice: 'squeak', diet: 'grubs', fee: 600, tags: ['Smelly', 'Cuddly', 'Diva'], traits: ['confident', 'stinky'], sigName: "Don't startle her", pre: 'Pew', suf: 'skunk', lbs: 8, bodySig: ['skunk'], kit: { plan: 'quad', L: 80, H: 34, leg: 14, lw: 10, col: '#24242a', pat: 'skunk', tail: 'skunk', headType: 'cat', hp: { col: '#24242a', skunk: 1, ears: 'small', eye: '#4a2a14', muz: '#3a3a40' } } });
sp('chupi', { name: 'El Chupi', sp: 'Chupacabra', cls: 'legend', act: 2, size: 2, cute: 3, scary: 3, hab: 'desert', voice: 'yip', diet: 'goat milk', fee: 9000, tags: ['Weird', 'Cuddly', 'Night owl'], traits: ['spooky', 'sweet'], sigName: 'Belly rubs', pre: 'Chupa', suf: 'cabra', lbs: 40, bodySig: ['spikes'], kit: { plan: 'quad', L: 92, H: 36, leg: 34, lw: 10, col: '#7a8a6a', skin: 'wrinkle', spikeCol: '#3a4a3a', bodyGrafts: ['spikes'], tail: 'thin', hp: { col: '#7a8a6a', bald: 1, ears: 'bat', earS: 1.1, er: 7.5, bugEyes: 1, snout: .5, eye: '#c03030', brows: false } } });
sp('jackalope', { name: 'Jack', sp: 'Jackalope', cls: 'legend', act: 2, size: 1, cute: 4, scary: 1, hab: 'desert', voice: 'tenor', diet: 'carrots', fee: 9000, tags: ['Jumper', 'Musical', 'Weird'], traits: ['musical', 'touchy'], sigName: 'Antler polish', pre: 'Jacka', suf: 'lope', lbs: 6, headSig: ['antlers'], kit: { plan: 'sit', W: 40, H: 44, col: '#b89a78', tail: 'stub', tailCol: '#f8f4ec', belly: '#efe2d0', headType: 'rabbit', headGrafts: ['antlers'], hp: { col: '#b89a78' } } });
for (const k in SP) { const s = SP[k]; if (s.kit.hp.headType) delete s.kit.hp.headType; s.headSig = s.headSig || []; s.bodySig = s.bodySig || []; s.ident = s.ident || []; }
const PETS = Object.keys(SP).filter(k => SP[k].cls === 'pet'), EXOTICS = Object.keys(SP).filter(k => SP[k].cls === 'exotic'), LEGENDS = Object.keys(SP).filter(k => SP[k].cls === 'legend');
const BREEDABLE = Object.keys(SP).filter(k => SP[k].cls !== 'sidekick');
const HABS = { kennel: 'Kennel', desert: 'Desert Run', swamp: 'Swamp Pool', reptile: 'Reptile Sauna', bigcat: 'Big Cat Deck', sky: 'Aviary Mast', mud: 'Mud Wallow', pachy: 'Pachyderm Hold', jungle: 'Jungle Deck', ice: 'Ice Room', salt: 'Saltwater Tank', jurassic: 'Jurassic Paddock' };
const HAB_COL = { kennel: ['#d8b07a', '#b8864e'], desert: ['#f0c890', '#d8a060'], swamp: ['#6ab0a0', '#3a7a6a'], reptile: ['#e8a060', '#c07040'], bigcat: ['#e8c070', '#b88a40'], sky: ['#9ad0f0', '#6aa0d0'], mud: ['#a88060', '#7a5a3a'], pachy: ['#c8b890', '#9a8a60'], jungle: ['#7ac070', '#4a8a4a'], ice: ['#d8f0ff', '#a0d0f0'], salt: ['#5aa0e0', '#2a70b0'], jurassic: ['#a8c070', '#7a9040'] };
// generic strays (keep the shelter a shelter all game)
const STRAY_NAMES = ['Nacho', 'Frijol', 'Pancho', 'Lupita', 'Chewy', 'Waffles', 'Pickles', 'Bandit', 'Nugget', 'Pepper', 'Mochi', 'Rocco', 'Bean', 'Tater Tot', 'Elote', 'Ziggy', 'Piñata', 'Gordo', 'Chispa', 'Turbo', 'Sprinkles', 'Mango', 'Coco', 'Burrito', 'Paleta', 'Dusty', 'Queso', 'Tortilla', 'Chimi', 'Gizmo', 'Sopapilla', 'Biscotti', 'Cheeto', 'Fajita', 'Noodles', 'Pretzel'];
const DOG_COLS = ['#c9955c', '#3a2e2a', '#f0e2c8', '#8a5a34', '#d8c8a8', '#a86a3a', '#5a4a40', '#e8c890'], CAT_COLS = ['#8a8a92', '#ee9a43', '#3a3436', '#f2e8dc', '#b89878', '#6a6a72'];
function strayKit(seedv, cat) {
  const r = (seedv * 9301 + 49297) % 233280; const f = n => ((r / (n + 3)) | 0) % 1000 / 1000;
  const col = (cat ? CAT_COLS : DOG_COLS)[Math.floor(f(1) * (cat ? CAT_COLS : DOG_COLS).length)];
  if (cat) return { plan: 'sit', W: 38 + f(2) * 8, H: 44 + f(3) * 10, col, tail: 'thin', pat: f(4) < .4 ? 'tabby' : null, patCol: dk(col, .3), belly: f(5) < .5 ? '#f8f2e8' : null, headType: 'cat', hp: { col, stripes: f(4) < .4 ? dk(col, .3) : null, eye: ['#9ab84a', '#e8c840', '#6ab0e0'][Math.floor(f(6) * 3)], tux: f(5) < .25 }, skin: 'fur' };
  const ears = ['up', 'flop', 'fold', 'bat'][Math.floor(f(7) * 4)];
  return { plan: f(8) < .7 ? 'sit' : 'quad', W: 40 + f(2) * 14, H: 46 + f(3) * 16, L: 90 + f(2) * 20, leg: 22 + f(3) * 14, lw: 12, col, tail: ['whip', 'bushy', 'curl'][Math.floor(f(9) * 3)], belly: f(5) < .6 ? lt(col, .5) : null, pat: f(4) < .2 ? 'spots' : null, hp: { col, snout: .2 + f(10) * .7, ears, muz: lt(col, .45), spot: f(11) < .3 ? dk(col, .35) : null, tongue: f(12) < .3, eye: '#4a2a14' }, skin: 'fur' };
}
